---
# Manifest file downloaded from fusionexternalId: c966afc5-7474-4ec6-aad6-ea43f99ea99c
externalId: upsert_assets_infor_from_cli_gh
name: upsert_assets_infor
query:
    file: raw_assets_infor.sql
destination:
    type: asset_hierarchy
ignoreNullFields: true
shared: true
action: upsert
# dataSetExternalId: src:002:infor:ds
authentication:
    clientId: ${COGNITE_CLIENT_ID}
    clientSecret: ${COGNITE_CLIENT_SECRET}
    tokenUrl: https://login.microsoftonline.com/16e3985b-ebe8-4e24-9da4-933e21a9fc81/oauth2/v2.0/token
  # Optional: If idP requires providing the scopes
    cdfProjectName: ${CDF_PROJECT_NAME}
    scopes:
        - https://greenfield.cognitedata.com/.default
