---
# Manifest file downloaded from fusionexternalId: tr-upsert_assets_sap
externalId: upsert_assets_sap_from_cli_gh
name: upsert_assets_sap
query:
    file: raw_assets_sap.sql
destination:
    type: asset_hierarchy
ignoreNullFields: true
shared: true
action: upsert
dataSetExternalId: src:001:sap:ds
authentication:
    clientId: ${COGNITE_CLIENT_ID}
    clientSecret: ${COGNITE_CLIENT_SECRET}
    tokenUrl: https://login.microsoftonline.com/16e3985b-ebe8-4e24-9da4-933e21a9fc81/oauth2/v2.0/token
  # Optional: If idP requires providing the scopes
    cdfProjectName: ${CDF_PROJECT_NAME}
    scopes:
        - https://greenfield.cognitedata.com/.default
